# Generated by Django 2.2.3 on 2019-07-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=10, null=True)),
                ('first_date', models.DateField(blank=True, db_column='First_Date', null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
    ]
