# Generated by Django 2.2.3 on 2019-07-31 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_auto_20190725_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('mvg', models.CharField(blank=True, max_length=10, null=True)),
                ('purchase_amount', models.FloatField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('캐릭터', models.FloatField(blank=True, null=True)),
                ('컨템포러리_여_field', models.FloatField(blank=True, db_column='컨템포러리(여)', null=True)),
                ('커리어', models.FloatField(blank=True, null=True)),
                ('엘레강스디자이너', models.FloatField(blank=True, null=True)),
                ('영캐릭터', models.FloatField(blank=True, null=True)),
                ('영캐주얼', models.FloatField(blank=True, null=True)),
                ('spa', models.FloatField(blank=True, db_column='SPA', null=True)),
                ('진유니', models.FloatField(blank=True, null=True)),
                ('정장셔츠', models.FloatField(blank=True, null=True)),
                ('남성캐주얼', models.FloatField(blank=True, null=True)),
                ('컨템포러리', models.FloatField(blank=True, null=True)),
                ('레져', models.FloatField(blank=True, null=True)),
                ('스포츠', models.FloatField(blank=True, null=True)),
                ('아동', models.FloatField(blank=True, null=True)),
                ('유아완구', models.FloatField(blank=True, null=True)),
                ('식품', models.FloatField(blank=True, null=True)),
                ('f_b', models.FloatField(blank=True, db_column='F&B', null=True)),
                ('가전', models.FloatField(blank=True, null=True)),
                ('가구', models.FloatField(blank=True, null=True)),
                ('주방', models.FloatField(blank=True, null=True)),
                ('식기홈데코', models.FloatField(blank=True, null=True)),
                ('홈패션', models.FloatField(blank=True, null=True)),
                ('패션잡화', models.FloatField(blank=True, null=True)),
                ('장신잡화', models.FloatField(blank=True, null=True)),
                ('구두', models.FloatField(blank=True, null=True)),
                ('핸드백', models.FloatField(blank=True, null=True)),
                ('화장품', models.FloatField(blank=True, null=True)),
                ('pb', models.FloatField(blank=True, db_column='PB', null=True)),
                ('롯데tops', models.FloatField(blank=True, db_column='롯데TOPS', null=True)),
            ],
            options={
                'db_table': 'Category',
                'managed': False,
            },
        ),
    ]
