# Generated by Django 2.2.3 on 2019-08-01 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
    ]
