# Generated by Django 2.2.3 on 2019-08-05 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0004_auto_20190801_0929'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
